<?php

// Konfigurasi mesin CRUD generik -- diekstrak 1:1 dari dictionary RES
// di portum.py (versi Python) supaya label, tipe field, opsi select,
// dan field mana yang wajib tetap identik dengan aplikasi lama.
// Dipakai oleh App\Http\Controllers\ModuleController.

return [
    'kendaraan' => [
        'model' => 'App\\Models\\UmKendaraan',
        'perm' => 'umum_rt',
        'modul' => 'Umum & Rumah Tangga',
        'judul' => 'Kendaraan & Driver',
        'maker_checker' => false,
        'fields' => [
            'no_polisi' => [
                'label' => 'No. Polisi',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'jenis' => [
                'label' => 'Jenis',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'merk' => [
                'label' => 'Merk',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'tahun' => [
                'label' => 'Tahun',
                'type' => 'text',
                'list' => false,
                'req' => false,
            ],
            'peruntukan' => [
                'label' => 'Peruntukan',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'driver' => [
                'label' => 'Driver',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Aktif', 'Servis', 'Nonaktif'],
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
        ],
    ],
    'biaya_harian' => [
        'model' => 'App\\Models\\UmBiayaHarian',
        'perm' => 'umum_rt',
        'modul' => 'Umum & Rumah Tangga',
        'judul' => 'Biaya BBM / Perawatan / Rumah Tangga',
        'maker_checker' => true,
        'fields' => [
            'tanggal' => [
                'label' => 'Tanggal',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => true,
            ],
            'kategori' => [
                'label' => 'Kategori',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => true,
                'opts' => ['BBM', 'Perawatan', 'Rumah Tangga', 'Kebersihan', 'Keamanan', 'Utilitas', 'Lainnya'],
            ],
            'kendaraan' => [
                'label' => 'Kendaraan',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'nama_beban' => [
                'label' => 'Nama Beban (Akun)',
                'type' => 'select',
                'list' => false,
                'req' => false,
                'opts_sql' => 'SELECT nama_beban AS v, nama_beban || " — " || rekening_debet AS t FROM ref_akun ORDER BY nama_beban',
            ],
            'rekening_debet' => [
                'label' => 'Rekening Debet',
                'type' => 'text',
                'list' => false,
                'req' => false,
            ],
            'rekening_kredit' => [
                'label' => 'Rekening Kredit',
                'type' => 'text',
                'list' => false,
                'req' => false,
            ],
            'uraian' => [
                'label' => 'Uraian',
                'type' => 'textarea',
                'list' => true,
                'req' => false,
            ],
            'jumlah' => [
                'label' => 'Jumlah',
                'type' => 'money',
                'list' => true,
                'fmt' => 'money',
                'req' => false,
            ],
            'no_nota' => [
                'label' => 'No. Nota',
                'type' => 'text',
                'list' => false,
                'req' => false,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Draft', 'Diajukan', 'Dibukukan'],
            ],
            'dibuat_oleh' => [
                'label' => 'Dibuat Oleh',
                'type' => 'auto_user',
                'list' => false,
                'req' => false,
            ],
            'dokumen' => [
                'label' => 'Dokumen (Lampiran)',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    // permintaan_cabang → DINONAKTIFKAN (digantikan oleh Ticketing per Fase 1)
    // Data lama tetap di tabel um_permintaan_cabang tapi tidak ditampilkan di menu.

    // ─────────────────────────────────────────────────────────────────────────────
    // MODUL BARU — Unit Kerja Umum & Rumah Tangga (perm: umum_rt)
    // ─────────────────────────────────────────────────────────────────────────────
    'fasilitas_kantor' => [
        'model'         => 'App\\Models\\UmFasilitasKantor',
        'perm'          => 'umum_rt',
        'modul'         => 'Umum & Rumah Tangga',
        'judul'         => 'Master Fasilitas Kantor',
        'maker_checker' => false,
        'fields'        => [
            'nama_fasilitas' => [
                'label' => 'Nama Fasilitas',
                'type'  => 'text',
                'list'  => true,
                'req'   => true,
            ],
            'kode' => [
                'label' => 'Kode',
                'type'  => 'text',
                'list'  => true,
                'req'   => false,
            ],
            'kategori' => [
                'label' => 'Kategori',
                'type'  => 'select',
                'list'  => true,
                'fmt'   => 'badge',
                'req'   => false,
                'opts'  => ['Ruangan', 'Peralatan', 'Furnitur', 'Elektronik', 'Kendaraan', 'Lainnya'],
            ],
            'lokasi' => [
                'label' => 'Lokasi',
                'type'  => 'text',
                'list'  => true,
                'req'   => false,
            ],
            'kondisi' => [
                'label' => 'Kondisi',
                'type'  => 'select',
                'list'  => true,
                'fmt'   => 'badge',
                'req'   => false,
                'opts'  => ['Baik', 'Perlu Perawatan', 'Rusak Ringan', 'Rusak Berat'],
            ],
            'tanggal_perolehan' => [
                'label' => 'Tgl Perolehan',
                'type'  => 'date',
                'list'  => false,
                'fmt'   => 'date',
                'req'   => false,
            ],
            'penanggung_jawab' => [
                'label' => 'Penanggung Jawab',
                'type'  => 'text',
                'list'  => false,
                'req'   => false,
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type'  => 'textarea',
                'list'  => false,
                'req'   => false,
            ],
        ],
    ],
    'pemeliharaan_gedung' => [
        'model'         => 'App\\Models\\UmPemeliharaanGedung',
        'perm'          => 'umum_rt',
        'modul'         => 'Umum & Rumah Tangga',
        'judul'         => 'Pemeliharaan Gedung & Utilitas',
        'maker_checker' => true,
        'fields'        => [
            'jenis_pekerjaan' => [
                'label' => 'Jenis Pekerjaan',
                'type'  => 'select',
                'list'  => true,
                'fmt'   => 'badge',
                'req'   => true,
                'opts'  => ['Gedung', 'Listrik', 'Air & Sanitasi', 'AC & Ventilasi', 'Lift', 'Taman', 'Lainnya'],
            ],
            'uraian' => [
                'label' => 'Uraian',
                'type'  => 'textarea',
                'list'  => true,
                'req'   => true,
            ],
            'lokasi' => [
                'label' => 'Lokasi',
                'type'  => 'text',
                'list'  => true,
                'req'   => false,
            ],
            'tanggal_rencana' => [
                'label' => 'Tgl Rencana',
                'type'  => 'date',
                'list'  => true,
                'fmt'   => 'date',
                'req'   => false,
            ],
            'tanggal_realisasi' => [
                'label' => 'Tgl Realisasi',
                'type'  => 'date',
                'list'  => true,
                'fmt'   => 'date',
                'req'   => false,
            ],
            'vendor' => [
                'label' => 'Vendor / Pelaksana',
                'type'  => 'text',
                'list'  => false,
                'req'   => false,
            ],
            'biaya' => [
                'label' => 'Biaya',
                'type'  => 'money',
                'list'  => true,
                'fmt'   => 'money',
                'req'   => false,
            ],
            'status' => [
                'label' => 'Status',
                'type'  => 'select',
                'list'  => true,
                'fmt'   => 'badge',
                'req'   => false,
                'opts'  => ['Dijadwalkan', 'Berjalan', 'Selesai', 'Ditunda'],
            ],
            'dokumen' => [
                'label' => 'Dokumen (Lampiran)',
                'type'  => 'file',
                'list'  => false,
                'req'   => false,
            ],
        ],
    ],
    'checklist_kebersihan' => [
        'model'         => 'App\\Models\\UmChecklistKebersihan',
        'perm'          => 'umum_rt',
        'modul'         => 'Umum & Rumah Tangga',
        'judul'         => 'Checklist Kebersihan & Keamanan',
        'maker_checker' => false,
        'fields'        => [
            'tanggal' => [
                'label'   => 'Tanggal',
                'type'    => 'date',
                'list'    => true,
                'fmt'     => 'date',
                'req'     => true,
                'default' => 'today',
            ],
            'jenis' => [
                'label' => 'Jenis',
                'type'  => 'select',
                'list'  => true,
                'fmt'   => 'badge',
                'req'   => true,
                'opts'  => ['Kebersihan Harian', 'Kebersihan Mingguan', 'Keamanan Harian', 'Keamanan Mingguan'],
            ],
            'area' => [
                'label' => 'Area',
                'type'  => 'text',
                'list'  => true,
                'req'   => false,
            ],
            'petugas' => [
                'label' => 'Petugas',
                'type'  => 'text',
                'list'  => true,
                'req'   => false,
            ],
            'status' => [
                'label' => 'Status',
                'type'  => 'select',
                'list'  => true,
                'fmt'   => 'badge',
                'req'   => false,
                'opts'  => ['Belum Dilakukan', 'Selesai', 'Ada Catatan'],
            ],
            'catatan' => [
                'label' => 'Catatan',
                'type'  => 'textarea',
                'list'  => false,
                'req'   => false,
            ],
            'dibuat_oleh' => [
                'label' => 'Dibuat Oleh',
                'type'  => 'auto_user',
                'list'  => false,
                'req'   => false,
            ],
        ],
    ],
    'k3_insiden' => [
        'model'         => 'App\\Models\\UmK3Insiden',
        'perm'          => 'umum_rt',
        'modul'         => 'Umum & Rumah Tangga',
        'judul'         => 'Catatan K3 & Lingkungan',
        'maker_checker' => false,
        'fields'        => [
            'tanggal' => [
                'label'   => 'Tanggal Kejadian',
                'type'    => 'date',
                'list'    => true,
                'fmt'     => 'date',
                'req'     => true,
                'default' => 'today',
            ],
            'jenis' => [
                'label' => 'Jenis',
                'type'  => 'select',
                'list'  => true,
                'fmt'   => 'badge',
                'req'   => true,
                'opts'  => ['Insiden K3', 'Near Miss', 'Isu Lingkungan', 'Isu Ergonomi', 'Lainnya'],
            ],
            'lokasi' => [
                'label' => 'Lokasi',
                'type'  => 'text',
                'list'  => true,
                'req'   => false,
            ],
            'uraian' => [
                'label' => 'Uraian Kejadian',
                'type'  => 'textarea',
                'list'  => true,
                'req'   => true,
            ],
            'korban' => [
                'label' => 'Korban / Yang Terdampak',
                'type'  => 'text',
                'list'  => false,
                'req'   => false,
            ],
            'tindak_lanjut' => [
                'label' => 'Tindak Lanjut',
                'type'  => 'textarea',
                'list'  => false,
                'req'   => false,
            ],
            'status' => [
                'label' => 'Status',
                'type'  => 'select',
                'list'  => true,
                'fmt'   => 'badge',
                'req'   => false,
                'opts'  => ['Open', 'Dalam Penanganan', 'Selesai'],
            ],
            'dokumen' => [
                'label' => 'Dokumen (Lampiran)',
                'type'  => 'file',
                'list'  => false,
                'req'   => false,
            ],
            'dibuat_oleh' => [
                'label' => 'Dilaporkan Oleh',
                'type'  => 'auto_user',
                'list'  => false,
                'req'   => false,
            ],
        ],
    ],
    'invoice_sewa' => [
        'model' => 'App\\Models\\AsInvoiceSewa',
        'perm' => 'logistik_pelaporan',
        'modul' => 'Logistik & Pelaporan',
        'judul' => 'Tagihan / Invoice Sewa',
        'maker_checker' => false,
        'fields' => [
            'no_invoice' => [
                'label' => 'No. Invoice',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'vendor' => [
                'label' => 'Vendor',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'jenis_sewa' => [
                'label' => 'Jenis Sewa',
                'type' => 'select',
                'list' => true,
                'req' => false,
                'opts' => ['Aplikasi', 'Mesin ATM', 'Brankas', 'Perangkat IT', 'Software', 'Hardware'],
            ],
            'periode_mulai' => [
                'label' => 'Periode Mulai',
                'type' => 'date',
                'list' => false,
                'req' => false,
            ],
            'periode_selesai' => [
                'label' => 'Periode Selesai',
                'type' => 'date',
                'list' => false,
                'req' => false,
            ],
            'nilai' => [
                'label' => 'Nilai',
                'type' => 'money',
                'list' => true,
                'fmt' => 'money',
                'req' => false,
            ],
            'jatuh_tempo' => [
                'label' => 'Jatuh Tempo',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => false,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Belum Bayar', 'Proses', 'Lunas'],
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
            'dokumen' => [
                'label' => 'Dokumen (Lampiran)',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    'aset' => [
        'model' => 'App\\Models\\AsAset',
        'perm' => 'administrasi_aset',
        'modul' => 'Administrasi Aset & Inventaris',
        'judul' => 'Inventarisasi Aset',
        'maker_checker' => false,
        'fields' => [
            'kode_aset' => [
                'label' => 'Kode Aset',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'nama_aset' => [
                'label' => 'Nama Aset',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'kategori' => [
                'label' => 'Kategori',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'lokasi' => [
                'label' => 'Lokasi',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'tanggal_perolehan' => [
                'label' => 'Tgl Perolehan',
                'type' => 'date',
                'list' => false,
                'fmt' => 'date',
                'req' => false,
            ],
            'nilai_perolehan' => [
                'label' => 'Nilai Perolehan',
                'type' => 'money',
                'list' => true,
                'fmt' => 'money',
                'req' => false,
            ],
            'umur_ekonomis' => [
                'label' => 'Umur Ekonomis (bln)',
                'type' => 'number',
                'list' => false,
                'req' => false,
            ],
            'kondisi' => [
                'label' => 'Kondisi',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Baik', 'Rusak Ringan', 'Rusak Berat'],
            ],
            'penanggung_jawab' => [
                'label' => 'Penanggung Jawab',
                'type' => 'text',
                'list' => false,
                'req' => false,
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
        ],
    ],
    'amortisasi' => [
        'model' => 'App\\Models\\AsAmortisasi',
        'perm' => 'administrasi_aset',
        'modul' => 'Administrasi Aset & Inventaris',
        'judul' => 'Amortisasi Biaya',
        'maker_checker' => false,
        'fields' => [
            'nama_biaya' => [
                'label' => 'Nama Biaya',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'nilai_perolehan' => [
                'label' => 'Nilai Perolehan',
                'type' => 'money',
                'list' => true,
                'fmt' => 'money',
                'req' => false,
            ],
            'tanggal_mulai' => [
                'label' => 'Tgl Mulai',
                'type' => 'date',
                'list' => false,
                'fmt' => 'date',
                'req' => false,
            ],
            'umur_bulan' => [
                'label' => 'Umur (bulan)',
                'type' => 'number',
                'list' => true,
                'req' => false,
            ],
            'nilai_per_bulan' => [
                'label' => 'Nilai / Bulan',
                'type' => 'money',
                'list' => true,
                'fmt' => 'money',
                'req' => false,
                'help' => 'Dihitung otomatis bila dikosongkan (nilai ÷ umur)',
            ],
            'akumulasi' => [
                'label' => 'Akumulasi',
                'type' => 'money',
                'list' => false,
                'fmt' => 'money',
                'req' => false,
            ],
            'nilai_buku' => [
                'label' => 'Nilai Buku',
                'type' => 'money',
                'list' => true,
                'fmt' => 'money',
                'req' => false,
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
        ],
    ],
    'pks' => [
        'model' => 'App\\Models\\AsPks',
        'perm' => 'logistik_pelaporan',
        'modul' => 'Logistik & Pelaporan',
        'judul' => 'PKS & Jatuh Tempo',
        'maker_checker' => true,
        'fields' => [
            'no_pks' => [
                'label' => 'No. PKS',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'judul' => [
                'label' => 'Judul PKS',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'vendor' => [
                'label' => 'Vendor / Pihak',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'div_owner' => [
                'label' => 'Divisi Owner',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'tanggal_mulai' => [
                'label' => 'Tgl Mulai',
                'type' => 'date',
                'list' => false,
                'fmt' => 'date',
                'req' => false,
            ],
            'jatuh_tempo' => [
                'label' => 'Jatuh Tempo',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => false,
            ],
            'nilai' => [
                'label' => 'Nilai',
                'type' => 'money',
                'list' => false,
                'fmt' => 'money',
                'req' => false,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Aktif', 'Akan Jatuh Tempo', 'Berakhir', 'Diperpanjang'],
            ],
            'memo_dibuat' => [
                'label' => 'Memo ke Div Owner Dibuat',
                'type' => 'checkbox',
                'list' => true,
                'req' => false,
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
            'dokumen' => [
                'label' => 'Dokumen (Lampiran)',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    'memo_sewa_cabang' => [
        'model' => 'App\\Models\\AsMemoSewaCabang',
        'perm' => 'logistik_pelaporan',
        'modul' => 'Logistik & Pelaporan',
        'judul' => 'Memo Sewa Cabang',
        'maker_checker' => true,
        'fields' => [
            'no_memo' => [
                'label' => 'No. Memo',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'cabang' => [
                'label' => 'Cabang',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'jenis' => [
                'label' => 'Jenis Sewa',
                'type' => 'select',
                'list' => true,
                'req' => false,
                'opts' => ['Galeri ATM', 'Gedung Kantor', 'Gudang', 'Rumah Dinas'],
            ],
            'tanggal' => [
                'label' => 'Tanggal',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => false,
            ],
            'nilai' => [
                'label' => 'Nilai',
                'type' => 'money',
                'list' => true,
                'fmt' => 'money',
                'req' => false,
            ],
            'status_persetujuan' => [
                'label' => 'Status Persetujuan',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Diajukan', 'Persetujuan Prinsip', 'Disetujui', 'Ditolak'],
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
            'dokumen' => [
                'label' => 'Dokumen (Lampiran)',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    'temuan' => [
        'model' => 'App\\Models\\AsTemuan',
        'perm' => 'administrasi_aset',
        'modul' => 'Administrasi Aset & Inventaris',
        'judul' => 'Tindak Lanjut Temuan',
        'maker_checker' => false,
        'fields' => [
            'no_temuan' => [
                'label' => 'No. Temuan',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'sumber' => [
                'label' => 'Sumber',
                'type' => 'select',
                'list' => true,
                'req' => false,
                'opts' => ['Audit Internal', 'OJK', 'KAP', 'Lainnya'],
            ],
            'uraian' => [
                'label' => 'Uraian Temuan',
                'type' => 'textarea',
                'list' => true,
                'req' => true,
            ],
            'tanggal_temuan' => [
                'label' => 'Tgl Temuan',
                'type' => 'date',
                'list' => false,
                'fmt' => 'date',
                'req' => false,
            ],
            'batas_tindak_lanjut' => [
                'label' => 'Batas Tindak Lanjut',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => false,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Open', 'Proses', 'Selesai'],
            ],
            'penanggung_jawab' => [
                'label' => 'Penanggung Jawab',
                'type' => 'text',
                'list' => false,
                'req' => false,
            ],
            'tindak_lanjut' => [
                'label' => 'Tindak Lanjut',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
            'dokumen' => [
                'label' => 'Dokumen (Lampiran)',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    'aset_history' => [
        'model' => 'App\\Models\\AsAsetHistory',
        'perm' => 'administrasi_aset',
        'modul' => 'Administrasi Aset & Inventaris',
        'judul' => 'Riwayat Pergerakan Aset',
        'maker_checker' => false,
        'fields' => [
            'aset_id' => [
                'label' => 'ID Aset',
                'type' => 'number',
                'list' => true,
                'req' => true,
            ],
            'field_changed' => [
                'label' => 'Perubahan',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'old_value' => [
                'label' => 'Nilai Lama',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'new_value' => [
                'label' => 'Nilai Baru',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type' => 'textarea',
                'list' => true,
                'req' => false,
            ],
            'changed_at' => [
                'label' => 'Waktu Perubahan',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => false,
            ],
        ],
    ],
    'mutasi_aset' => [
        'model' => 'App\\Models\\AsMutasiAset',
        'perm' => 'administrasi_aset',
        'modul' => 'Administrasi Aset & Inventaris',
        'judul' => 'Mutasi Aset',
        'maker_checker' => true,
        'fields' => [
            'no_mutasi' => [
                'label' => 'No. Mutasi',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'aset_id' => [
                'label' => 'ID Aset',
                'type' => 'number',
                'list' => true,
                'req' => true,
            ],
            'dari_lokasi' => [
                'label' => 'Dari Lokasi',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'ke_lokasi' => [
                'label' => 'Ke Lokasi',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'dari_penanggung_jawab' => [
                'label' => 'Dari PJ',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'ke_penanggung_jawab' => [
                'label' => 'Ke PJ',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'alasan' => [
                'label' => 'Alasan Mutasi',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Diajukan', 'Disetujui', 'Ditolak', 'Selesai'],
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
            'dokumen' => [
                'label' => 'Dokumen Berita Acara',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    'disposal_aset' => [
        'model' => 'App\\Models\\AsDisposalAset',
        'perm' => 'administrasi_aset',
        'modul' => 'Administrasi Aset & Inventaris',
        'judul' => 'Penghapusan Aset (Disposal)',
        'maker_checker' => true,
        'fields' => [
            'no_disposal' => [
                'label' => 'No. Disposal',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'aset_id' => [
                'label' => 'ID Aset',
                'type' => 'number',
                'list' => true,
                'req' => true,
            ],
            'tanggal_pengajuan' => [
                'label' => 'Tgl Pengajuan',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => false,
            ],
            'alasan_penghapusan' => [
                'label' => 'Alasan Penghapusan',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'metode' => [
                'label' => 'Metode',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Dihibahkan', 'Dijual', 'Dimusnahkan', 'Dihapusbukukan'],
            ],
            'nilai_buku_terakhir' => [
                'label' => 'Nilai Buku Terakhir',
                'type' => 'money',
                'list' => true,
                'fmt' => 'money',
                'req' => false,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Diajukan', 'Disetujui', 'Ditolak', 'Selesai'],
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
            'dokumen' => [
                'label' => 'Dokumen SK / Berita Acara',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    'rekonsiliasi_aset' => [
        'model' => 'App\\Models\\AsRekonsiliasiAset',
        'perm' => 'administrasi_aset',
        'modul' => 'Administrasi Aset & Inventaris',
        'judul' => 'Rekonsiliasi & Reklasifikasi Aset',
        'maker_checker' => false,
        'fields' => [
            'no_rekonsiliasi' => [
                'label' => 'No. Rekonsiliasi',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'periode' => [
                'label' => 'Periode',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'tanggal' => [
                'label' => 'Tanggal',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => false,
            ],
            'jenis' => [
                'label' => 'Jenis Kegiatan',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Rekonsiliasi', 'Reklasifikasi'],
            ],
            'aset_id' => [
                'label' => 'ID Aset',
                'type' => 'number',
                'list' => false,
                'req' => false,
            ],
            'kategori_awal' => [
                'label' => 'Kategori Semula',
                'type' => 'text',
                'list' => false,
                'req' => false,
            ],
            'kategori_baru' => [
                'label' => 'Kategori Baru',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'kondisi_awal' => [
                'label' => 'Kondisi Semula',
                'type' => 'select',
                'list' => false,
                'req' => false,
                'opts' => ['Baik', 'Rusak Ringan', 'Rusak Berat'],
            ],
            'kondisi_baru' => [
                'label' => 'Kondisi Hasil Cek',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Baik', 'Rusak Ringan', 'Rusak Berat'],
            ],
            'hasil_rekonsiliasi' => [
                'label' => 'Hasil Rekonsiliasi',
                'type' => 'textarea',
                'list' => true,
                'req' => false,
            ],
            'petugas' => [
                'label' => 'Petugas Pemeriksa',
                'type' => 'text',
                'list' => false,
                'req' => false,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Proses', 'Selesai'],
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
            'dokumen' => [
                'label' => 'Dokumen Rekon / BA',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    'penerimaan_barang' => [
        'model' => 'App\\Models\\AsPenerimaanBarang',
        'perm' => 'logistik_pelaporan',
        'modul' => 'Logistik & Pelaporan',
        'judul' => 'Penerimaan Barang / Jasa',
        'maker_checker' => false,
        'fields' => [
            'no_penerimaan' => [
                'label' => 'No. Penerimaan',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'tanggal' => [
                'label' => 'Tanggal Masuk',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => false,
            ],
            'vendor' => [
                'label' => 'Vendor / Penyedia',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'nama_barang' => [
                'label' => 'Nama Barang / Jasa',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'jumlah' => [
                'label' => 'Jumlah',
                'type' => 'number',
                'list' => true,
                'req' => false,
            ],
            'satuan' => [
                'label' => 'Satuan',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'kondisi' => [
                'label' => 'Kondisi Barang',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Baik', 'Rusak', 'Tidak Sesuai'],
            ],
            'penerima' => [
                'label' => 'Penerima',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Diterima', 'Diperiksa', 'Disimpan'],
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
            'dokumen' => [
                'label' => 'Surat Jalan / BAST',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    'distribusi_barang' => [
        'model' => 'App\\Models\\AsDistribusiBarang',
        'perm' => 'logistik_pelaporan',
        'modul' => 'Logistik & Pelaporan',
        'judul' => 'Distribusi Barang / Jasa',
        'maker_checker' => false,
        'fields' => [
            'no_distribusi' => [
                'label' => 'No. Distribusi',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'tanggal' => [
                'label' => 'Tanggal Keluar',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => false,
            ],
            'nama_barang' => [
                'label' => 'Nama Barang / Jasa',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'jumlah' => [
                'label' => 'Jumlah',
                'type' => 'number',
                'list' => true,
                'req' => false,
            ],
            'satuan' => [
                'label' => 'Satuan',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'tujuan_unit' => [
                'label' => 'Unit / Cabang Tujuan',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'penerima' => [
                'label' => 'Nama Penerima',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Disiapkan', 'Terkirim', 'Diterima'],
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
            'dokumen' => [
                'label' => 'Tanda Terima / Ekspedisi',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    'pembayaran_tagihan' => [
        'model' => 'App\\Models\\AsPembayaranTagihan',
        'perm' => 'logistik_pelaporan',
        'modul' => 'Logistik & Pelaporan',
        'judul' => 'Administrasi Pembayaran Tagihan',
        'maker_checker' => true,
        'fields' => [
            'no_tagihan' => [
                'label' => 'No. Tagihan',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'tanggal_tagihan' => [
                'label' => 'Tgl Tagihan',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => false,
            ],
            'tanggal_bayar' => [
                'label' => 'Tgl Bayar',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => false,
            ],
            'vendor' => [
                'label' => 'Vendor / Rekanan',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'uraian' => [
                'label' => 'Uraian Pembayaran',
                'type' => 'textarea',
                'list' => true,
                'req' => false,
            ],
            'nilai' => [
                'label' => 'Nilai Tagihan',
                'type' => 'money',
                'list' => true,
                'fmt' => 'money',
                'req' => true,
            ],
            'no_rekening' => [
                'label' => 'No. Rekening Tujuan',
                'type' => 'text',
                'list' => false,
                'req' => false,
            ],
            'status' => [
                'label' => 'Status Pembayaran',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Belum Bayar', 'Proses', 'Lunas'],
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
            'dokumen' => [
                'label' => 'Bukti Bayar / Kuitansi',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    'memo_internal' => [
        'model' => 'App\\Models\\PgMemoInternal',
        'perm' => 'pengadaan',
        'modul' => 'Pengadaan & Pemeliharaan',
        'judul' => 'Memo Internal',
        'maker_checker' => false,
        'fields' => [
            'no_memo' => [
                'label' => 'No. Memo',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'dari_unit' => [
                'label' => 'Dari Unit',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'ke_unit' => [
                'label' => 'Ke Unit',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'perihal' => [
                'label' => 'Perihal',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'tanggal' => [
                'label' => 'Tanggal',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => false,
            ],
            'jenis' => [
                'label' => 'Jenis',
                'type' => 'select',
                'list' => false,
                'req' => false,
                'opts' => ['Divisi', 'Cabang', 'Cabang Pembantu', 'Kantor Kas'],
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Masuk', 'Diproses', 'Selesai'],
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
            'dokumen' => [
                'label' => 'Dokumen (Lampiran)',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    'penawaran' => [
        'model' => 'App\\Models\\PgPenawaran',
        'perm' => 'pengadaan',
        'modul' => 'Pengadaan & Pemeliharaan',
        'judul' => 'Penawaran Vendor',
        'maker_checker' => false,
        'fields' => [
            'no_penawaran' => [
                'label' => 'No. Penawaran',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'vendor' => [
                'label' => 'Vendor',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'barang_jasa' => [
                'label' => 'Barang / Jasa',
                'type' => 'textarea',
                'list' => true,
                'req' => false,
            ],
            'nilai' => [
                'label' => 'Nilai Penawaran',
                'type' => 'money',
                'list' => true,
                'fmt' => 'money',
                'req' => false,
            ],
            'tanggal' => [
                'label' => 'Tanggal',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => false,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Diterima', 'Evaluasi', 'Negosiasi', 'Ditolak'],
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
            'dokumen' => [
                'label' => 'Dokumen (Lampiran)',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    'negosiasi' => [
        'model' => 'App\\Models\\PgNegosiasi',
        'perm' => 'pengadaan',
        'modul' => 'Pengadaan & Pemeliharaan',
        'judul' => 'Negosiasi (Berita Acara)',
        'maker_checker' => false,
        'fields' => [
            'no_berita_acara' => [
                'label' => 'No. Berita Acara',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'vendor' => [
                'label' => 'Vendor',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'barang_jasa' => [
                'label' => 'Barang / Jasa',
                'type' => 'textarea',
                'list' => true,
                'req' => false,
            ],
            'nilai_awal' => [
                'label' => 'Nilai Awal',
                'type' => 'money',
                'list' => true,
                'fmt' => 'money',
                'req' => false,
            ],
            'nilai_nego' => [
                'label' => 'Nilai Nego',
                'type' => 'money',
                'list' => true,
                'fmt' => 'money',
                'req' => false,
            ],
            'tanggal' => [
                'label' => 'Tanggal',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => false,
            ],
            'hasil' => [
                'label' => 'Hasil',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
            'dokumen' => [
                'label' => 'Dokumen (Lampiran)',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    'draft_dokumen' => [
        'model' => 'App\\Models\\PgDraftDokumen',
        'perm' => 'pengadaan',
        'modul' => 'Pengadaan & Pemeliharaan',
        'judul' => 'Draft Dokumen (PKS/NDA/SPK)',
        'maker_checker' => false,
        'fields' => [
            'jenis' => [
                'label' => 'Jenis',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['PKS', 'NDA', 'SPK', 'Lainnya'],
            ],
            'no_dokumen' => [
                'label' => 'No. Dokumen',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'judul' => [
                'label' => 'Judul',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'vendor' => [
                'label' => 'Vendor',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'tanggal' => [
                'label' => 'Tanggal',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => false,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Draft', 'Review', 'Final'],
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
            'file' => [
                'label' => 'Dokumen (Lampiran)',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    'spk' => [
        'model' => 'App\\Models\\PgSpk',
        'perm' => 'pengadaan',
        'modul' => 'Pengadaan & Pemeliharaan',
        'judul' => 'SPK (Surat Perintah Kerja)',
        'maker_checker' => true,
        'fields' => [
            'no_spk' => [
                'label' => 'No. SPK',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'vendor' => [
                'label' => 'Vendor',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'pekerjaan' => [
                'label' => 'Pekerjaan',
                'type' => 'textarea',
                'list' => true,
                'req' => false,
            ],
            'nilai' => [
                'label' => 'Nilai',
                'type' => 'money',
                'list' => true,
                'fmt' => 'money',
                'req' => false,
            ],
            'tanggal_terbit' => [
                'label' => 'Tgl Terbit',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => false,
            ],
            'tanggal_selesai' => [
                'label' => 'Tgl Selesai',
                'type' => 'date',
                'list' => false,
                'fmt' => 'date',
                'req' => false,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Berjalan', 'Selesai', 'Batal'],
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
            'dokumen' => [
                'label' => 'Dokumen (Lampiran)',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    'reminder' => [
        'model' => 'App\\Models\\PgReminder',
        'perm' => 'pengadaan',
        'modul' => 'Pengadaan & Pemeliharaan',
        'judul' => 'Reminder Schedule',
        'maker_checker' => false,
        'fields' => [
            'judul' => [
                'label' => 'Judul',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'kategori' => [
                'label' => 'Kategori',
                'type' => 'select',
                'list' => true,
                'req' => true,
                'opts' => ['PKS', 'Sewa', 'SPK', 'Pemeliharaan', 'Lainnya'],
            ],
            'tanggal_jatuh_tempo' => [
                'label' => 'Tgl Jatuh Tempo',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => true,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Aktif', 'Selesai'],
            ],
            'catatan' => [
                'label' => 'Catatan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
        ],
    ],
    'ref_akun' => [
        'model' => 'App\\Models\\RefAkun',
        'perm' => 'ref_akun',
        'modul' => 'Pengaturan',
        'judul' => 'Referensi Akun Biaya',
        'maker_checker' => false,
        'fields' => [
            'nama_beban' => [
                'label' => 'Nama Beban',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'rekening_debet' => [
                'label' => 'Rekening Debet',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'contoh_keterangan' => [
                'label' => 'Contoh Keterangan',
                'type' => 'textarea',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    // ─────────────────────────────────────────────────────────────────────────────
    // MODUL ARSIP SURAT & MEMO — Unit Kerja Dokumen & Kearsipan (perm: dokumen_arsip)
    // ─────────────────────────────────────────────────────────────────────────────
    'surat_masuk' => [
        'model' => 'App\\Models\\SrSuratMasuk',
        'perm' => 'dokumen_arsip',
        'modul' => 'Dokumen & Kearsipan',
        'judul' => 'Surat Masuk',
        'maker_checker' => false,
        'fields' => [
            'nomor_agenda' => [
                'label' => 'Nomor Agenda',
                'type' => 'number',
                'list' => true,
                'req' => true,
                'help' => 'Rekomendasi otomatis (+10 setiap hari baru, +1 di hari yang sama) — boleh diubah / disisip nomor untuk tanggal sebelumnya.',
            ],
            'no_surat' => [
                'label' => 'No. Surat',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'pengirim' => [
                'label' => 'Pengirim',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'perihal' => [
                'label' => 'Perihal',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'tanggal' => [
                'label' => 'Tanggal',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => true,
                'default' => 'today',
            ],
            'penerima' => [
                'label' => 'Penerima',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'lokasi_arsip' => [
                'label' => 'Lokasi Arsip',
                'type' => 'text',
                'list' => true,
                'req' => false,
                'help' => 'cth: Lemari A / Ordner 3 / Map Merah',
            ],
            'masa_retensi' => [
                'label' => 'Masa Retensi (tahun)',
                'type'  => 'number',
                'list'  => false,
                'req'   => false,
            ],
            'status_arsip' => [
                'label' => 'Status Arsip',
                'type'  => 'select',
                'list'  => true,
                'fmt'   => 'badge',
                'req'   => false,
                'opts'  => ['Aktif', 'Arsip', 'Musnah'],
            ],
            'lampiran' => [
                'label' => 'Lampiran',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
            'dibuat_oleh' => [
                'label' => 'Dibuat Oleh',
                'type' => 'auto_user',
                'list' => false,
                'req' => false,
            ],
        ],
    ],
    'surat_keluar' => [
        'model' => 'App\\Models\\SrSuratKeluar',
        'perm' => 'dokumen_arsip',
        'modul' => 'Dokumen & Kearsipan',
        'judul' => 'Surat Keluar',
        'maker_checker' => false,
        'fields' => [
            'nomor_agenda' => [
                'label' => 'Nomor Agenda',
                'type' => 'number',
                'list' => true,
                'req' => true,
                'help' => 'Rekomendasi otomatis (+10 setiap hari baru, +1 di hari yang sama) — boleh diubah / disisip nomor untuk tanggal sebelumnya.',
            ],
            'no_surat' => [
                'label' => 'No. Surat',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'pengirim' => [
                'label' => 'Pengirim (Unit)',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'perihal' => [
                'label' => 'Perihal',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'tanggal' => [
                'label' => 'Tanggal',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => true,
                'default' => 'today',
            ],
            'penerima' => [
                'label' => 'Penerima / Tujuan',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'lokasi_arsip' => [
                'label' => 'Lokasi Arsip',
                'type' => 'text',
                'list' => true,
                'req' => false,
                'help' => 'cth: Lemari A / Ordner 3 / Map Merah',
            ],
            'masa_retensi' => [
                'label' => 'Masa Retensi (tahun)',
                'type'  => 'number',
                'list'  => false,
                'req'   => false,
            ],
            'status_arsip' => [
                'label' => 'Status Arsip',
                'type'  => 'select',
                'list'  => true,
                'fmt'   => 'badge',
                'req'   => false,
                'opts'  => ['Aktif', 'Arsip', 'Musnah'],
            ],
            'lampiran' => [
                'label' => 'Lampiran',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
            'dibuat_oleh' => [
                'label' => 'Dibuat Oleh',
                'type' => 'auto_user',
                'list' => false,
                'req' => false,
            ],
        ],
    ],
    'memo_masuk' => [
        'model' => 'App\\Models\\SrMemoMasuk',
        'perm' => 'dokumen_arsip',
        'modul' => 'Dokumen & Kearsipan',
        'judul' => 'Memo Masuk',
        'maker_checker' => false,
        'fields' => [
            'nomor_agenda' => [
                'label' => 'Nomor Agenda',
                'type' => 'number',
                'list' => true,
                'req' => true,
                'help' => 'Rekomendasi otomatis (+10 setiap hari baru, +1 di hari yang sama) — boleh diubah / disisip nomor untuk tanggal sebelumnya.',
            ],
            'no_surat' => [
                'label' => 'No. Surat',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'pengirim' => [
                'label' => 'Pengirim',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'perihal' => [
                'label' => 'Perihal',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'tanggal' => [
                'label' => 'Tanggal',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => true,
                'default' => 'today',
            ],
            'penerima' => [
                'label' => 'Penerima',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'lokasi_arsip' => [
                'label' => 'Lokasi Arsip',
                'type' => 'text',
                'list' => true,
                'req' => false,
                'help' => 'cth: Lemari A / Ordner 3 / Map Merah',
            ],
            'masa_retensi' => [
                'label' => 'Masa Retensi (tahun)',
                'type'  => 'number',
                'list'  => false,
                'req'   => false,
            ],
            'status_arsip' => [
                'label' => 'Status Arsip',
                'type'  => 'select',
                'list'  => true,
                'fmt'   => 'badge',
                'req'   => false,
                'opts'  => ['Aktif', 'Arsip', 'Musnah'],
            ],
            'lampiran' => [
                'label' => 'Lampiran',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
            'dibuat_oleh' => [
                'label' => 'Dibuat Oleh',
                'type' => 'auto_user',
                'list' => false,
                'req' => false,
            ],
        ],
    ],
    'memo_keluar' => [
        'model' => 'App\\Models\\SrMemoKeluar',
        'perm' => 'dokumen_arsip',
        'modul' => 'Dokumen & Kearsipan',
        'judul' => 'Memo Keluar',
        'maker_checker' => false,
        'fields' => [
            'nomor_agenda' => [
                'label' => 'Nomor Agenda',
                'type' => 'number',
                'list' => true,
                'req' => true,
                'help' => 'Rekomendasi otomatis (+10 setiap hari baru, +1 di hari yang sama) — boleh diubah / disisip nomor untuk tanggal sebelumnya.',
            ],
            'no_surat' => [
                'label' => 'No. Surat',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'pengirim' => [
                'label' => 'Pengirim (Unit)',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'perihal' => [
                'label' => 'Perihal',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'tanggal' => [
                'label' => 'Tanggal',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => true,
                'default' => 'today',
            ],
            'penerima' => [
                'label' => 'Penerima / Tujuan',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'lokasi_arsip' => [
                'label' => 'Lokasi Arsip',
                'type' => 'text',
                'list' => true,
                'req' => false,
                'help' => 'cth: Lemari A / Ordner 3 / Map Merah',
            ],
            'masa_retensi' => [
                'label' => 'Masa Retensi (tahun)',
                'type'  => 'number',
                'list'  => false,
                'req'   => false,
            ],
            'status_arsip' => [
                'label' => 'Status Arsip',
                'type'  => 'select',
                'list'  => true,
                'fmt'   => 'badge',
                'req'   => false,
                'opts'  => ['Aktif', 'Arsip', 'Musnah'],
            ],
            'lampiran' => [
                'label' => 'Lampiran',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
            'dibuat_oleh' => [
                'label' => 'Dibuat Oleh',
                'type' => 'auto_user',
                'list' => false,
                'req' => false,
            ],
        ],
    ],
    // ─────────────────────────────────────────────────────────────────────────────
    // MODUL BARU — Unit Kerja Dokumen & Kearsipan (perm: dokumen_arsip)
    // ─────────────────────────────────────────────────────────────────────────────
    'arsip_dokumen' => [
        'model'         => 'App\\Models\\DkArsipDokumen',
        'perm'          => 'dokumen_arsip',
        'modul'         => 'Dokumen & Kearsipan',
        'judul'         => 'Master Arsip Dokumen',
        'maker_checker' => false,
        'fields'        => [
            'kode_arsip' => [
                'label' => 'Kode Arsip',
                'type'  => 'text',
                'list'  => true,
                'req'   => false,
            ],
            'judul' => [
                'label' => 'Judul Dokumen',
                'type'  => 'text',
                'list'  => true,
                'req'   => true,
            ],
            'jenis' => [
                'label' => 'Jenis',
                'type'  => 'select',
                'list'  => true,
                'fmt'   => 'badge',
                'req'   => false,
                'opts'  => ['Fisik', 'Digital', 'Fisik & Digital'],
            ],
            'kategori' => [
                'label' => 'Kategori',
                'type'  => 'select',
                'list'  => true,
                'req'   => false,
                'opts'  => ['Surat', 'Memo', 'Kontrak', 'Laporan', 'SK', 'Kebijakan', 'Lainnya'],
            ],
            'tanggal_dokumen' => [
                'label' => 'Tanggal Dokumen',
                'type'  => 'date',
                'list'  => true,
                'fmt'   => 'date',
                'req'   => false,
            ],
            'lokasi_arsip' => [
                'label' => 'Lokasi Arsip',
                'type'  => 'text',
                'list'  => true,
                'req'   => false,
                'help'  => 'cth: Lemari A / Ordner 3 / Map Merah',
            ],
            'masa_retensi' => [
                'label' => 'Masa Retensi (tahun)',
                'type'  => 'number',
                'list'  => false,
                'req'   => false,
            ],
            'status_arsip' => [
                'label' => 'Status Arsip',
                'type'  => 'select',
                'list'  => true,
                'fmt'   => 'badge',
                'req'   => false,
                'opts'  => ['Aktif', 'Arsip', 'Musnah'],
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type'  => 'textarea',
                'list'  => false,
                'req'   => false,
            ],
            'lampiran' => [
                'label' => 'File Digital',
                'type'  => 'file',
                'list'  => false,
                'req'   => false,
            ],
            'dibuat_oleh' => [
                'label' => 'Diinput Oleh',
                'type'  => 'auto_user',
                'list'  => false,
                'req'   => false,
            ],
        ],
    ],
    'dokumen_legalitas' => [
        'model'         => 'App\\Models\\DkDokumenLegalitas',
        'perm'          => 'dokumen_arsip',
        'modul'         => 'Dokumen & Kearsipan',
        'judul'         => 'Dokumen Legalitas',
        'maker_checker' => false,
        'fields'        => [
            'nama_dokumen' => [
                'label' => 'Nama Dokumen',
                'type'  => 'text',
                'list'  => true,
                'req'   => true,
            ],
            'jenis' => [
                'label' => 'Jenis',
                'type'  => 'select',
                'list'  => true,
                'fmt'   => 'badge',
                'req'   => false,
                'opts'  => ['Izin Usaha', 'Sertifikat', 'NPWP', 'Akta', 'SK', 'Lisensi', 'Lainnya'],
            ],
            'no_dokumen' => [
                'label' => 'No. Dokumen',
                'type'  => 'text',
                'list'  => true,
                'req'   => false,
            ],
            'penerbit' => [
                'label' => 'Penerbit / Instansi',
                'type'  => 'text',
                'list'  => true,
                'req'   => false,
            ],
            'tanggal_terbit' => [
                'label' => 'Tgl Terbit',
                'type'  => 'date',
                'list'  => true,
                'fmt'   => 'date',
                'req'   => false,
            ],
            'tanggal_berlaku' => [
                'label' => 'Tgl Berlaku Sampai',
                'type'  => 'date',
                'list'  => true,
                'fmt'   => 'date',
                'req'   => false,
            ],
            'status' => [
                'label' => 'Status',
                'type'  => 'select',
                'list'  => true,
                'fmt'   => 'badge',
                'req'   => false,
                'opts'  => ['Aktif', 'Akan Kadaluarsa', 'Kadaluarsa', 'Diperpanjang'],
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type'  => 'textarea',
                'list'  => false,
                'req'   => false,
            ],
            'dokumen' => [
                'label' => 'Dokumen (Lampiran)',
                'type'  => 'file',
                'list'  => false,
                'req'   => false,
            ],
        ],
    ],
    // ─────────────────────────────────────────────────────────────────────────────
    // MODUL PENGADAAN — Unit Kerja Pengadaan Aset & Inventaris (perm: pengadaan)
    // Modul tambahan (opsional): Perencanaan Kebutuhan
    // ─────────────────────────────────────────────────────────────────────────────
    'perencanaan_kebutuhan' => [
        'model'         => 'App\\Models\\PmPerencanaanKebutuhan',
        'perm'          => 'pengadaan',
        'modul'         => 'Pengadaan & Pemeliharaan',
        'judul'         => 'Perencanaan Kebutuhan',
        'maker_checker' => false,
        'fields'        => [
            'no_rencana' => [
                'label' => 'No. Rencana',
                'type'  => 'text',
                'list'  => true,
                'req'   => false,
            ],
            'periode' => [
                'label' => 'Periode',
                'type'  => 'text',
                'list'  => true,
                'req'   => false,
                'help'  => 'cth: Q1 2026 / Semester I 2026',
            ],
            'jenis_kebutuhan' => [
                'label' => 'Jenis Kebutuhan',
                'type'  => 'select',
                'list'  => true,
                'fmt'   => 'badge',
                'req'   => false,
                'opts'  => ['Barang', 'Jasa', 'Aset'],
            ],
            'nama_item' => [
                'label' => 'Nama Barang / Jasa / Aset',
                'type'  => 'text',
                'list'  => true,
                'req'   => true,
            ],
            'jumlah' => [
                'label' => 'Jumlah',
                'type'  => 'number',
                'list'  => true,
                'req'   => false,
            ],
            'satuan' => [
                'label' => 'Satuan',
                'type'  => 'text',
                'list'  => true,
                'req'   => false,
            ],
            'spesifikasi' => [
                'label' => 'Spesifikasi / Keterangan',
                'type'  => 'textarea',
                'list'  => false,
                'req'   => false,
            ],
            'estimasi_harga' => [
                'label' => 'Estimasi Harga',
                'type'  => 'money',
                'list'  => true,
                'fmt'   => 'money',
                'req'   => false,
            ],
            'prioritas' => [
                'label' => 'Prioritas',
                'type'  => 'select',
                'list'  => true,
                'fmt'   => 'badge',
                'req'   => false,
                'opts'  => ['Darurat', 'Tinggi', 'Normal', 'Rendah'],
            ],
            'status' => [
                'label' => 'Status',
                'type'  => 'select',
                'list'  => true,
                'fmt'   => 'badge',
                'req'   => false,
                'opts'  => ['Draft', 'Diajukan', 'Disetujui', 'Ditolak', 'Selesai'],
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type'  => 'textarea',
                'list'  => false,
                'req'   => false,
            ],
        ],
    ],
    // ─────────────────────────────────────────────────────────────────────────────
    // MODUL PEMELIHARAAN — Unit Kerja Pemeliharaan & Pengawasan (perm: pemeliharaan_pengawasan)
    // ─────────────────────────────────────────────────────────────────────────────
    'jadwal_pemeliharaan' => [
        'model'         => 'App\\Models\\PmJadwalPemeliharaan',
        'perm'          => 'pemeliharaan_pengawasan',
        'modul'         => 'Pemeliharaan & Pengawasan',
        'judul'         => 'Jadwal Pemeliharaan Rutin',
        'maker_checker' => false,
        'fields'        => [
            'no_jadwal' => [
                'label' => 'No. Jadwal',
                'type'  => 'text',
                'list'  => true,
                'req'   => false,
            ],
            'nama_aset' => [
                'label' => 'Nama Aset',
                'type'  => 'text',
                'list'  => true,
                'req'   => false,
                'help'  => 'Nama atau kode aset yang akan dipelihara',
            ],
            'jenis_pemeliharaan' => [
                'label' => 'Jenis Pemeliharaan',
                'type'  => 'select',
                'list'  => true,
                'fmt'   => 'badge',
                'req'   => false,
                'opts'  => ['Rutin', 'Insidental', 'Preventif', 'Korektif'],
            ],
            'tanggal_rencana' => [
                'label' => 'Tgl Rencana',
                'type'  => 'date',
                'list'  => true,
                'fmt'   => 'date',
                'req'   => false,
            ],
            'tanggal_realisasi' => [
                'label' => 'Tgl Realisasi',
                'type'  => 'date',
                'list'  => true,
                'fmt'   => 'date',
                'req'   => false,
            ],
            'pelaksana' => [
                'label' => 'Pelaksana',
                'type'  => 'text',
                'list'  => true,
                'req'   => false,
            ],
            'status' => [
                'label' => 'Status',
                'type'  => 'select',
                'list'  => true,
                'fmt'   => 'badge',
                'req'   => false,
                'opts'  => ['Direncanakan', 'Dikerjakan', 'Selesai', 'Dibatalkan'],
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type'  => 'textarea',
                'list'  => false,
                'req'   => false,
            ],
            'dokumen' => [
                'label' => 'Dokumen / Laporan',
                'type'  => 'file',
                'list'  => false,
                'req'   => false,
            ],
        ],
    ],
    'monitoring_kondisi' => [
        'model'         => 'App\\Models\\PmMonitoringKondisi',
        'perm'          => 'pemeliharaan_pengawasan',
        'modul'         => 'Pemeliharaan & Pengawasan',
        'judul'         => 'Monitoring Kondisi Fisik Aset',
        'maker_checker' => false,
        'fields'        => [
            'nama_aset' => [
                'label' => 'Nama Aset',
                'type'  => 'text',
                'list'  => true,
                'req'   => false,
            ],
            'tanggal_inspeksi' => [
                'label' => 'Tgl Inspeksi',
                'type'  => 'date',
                'list'  => true,
                'fmt'   => 'date',
                'req'   => true,
                'default' => 'today',
            ],
            'kondisi' => [
                'label' => 'Kondisi',
                'type'  => 'select',
                'list'  => true,
                'fmt'   => 'badge',
                'req'   => false,
                'opts'  => ['Baik', 'Rusak Ringan', 'Rusak Berat'],
            ],
            'temuan' => [
                'label' => 'Temuan',
                'type'  => 'textarea',
                'list'  => true,
                'req'   => false,
            ],
            'rekomendasi' => [
                'label' => 'Rekomendasi',
                'type'  => 'textarea',
                'list'  => false,
                'req'   => false,
            ],
            'petugas' => [
                'label' => 'Petugas Pemeriksa',
                'type'  => 'text',
                'list'  => true,
                'req'   => false,
            ],
            'status' => [
                'label' => 'Status',
                'type'  => 'select',
                'list'  => true,
                'fmt'   => 'badge',
                'req'   => false,
                'opts'  => ['Selesai', 'Perlu Tindak Lanjut'],
            ],
            'dokumen' => [
                'label' => 'Foto / Dokumen',
                'type'  => 'file',
                'list'  => false,
                'req'   => false,
            ],
        ],
    ],
    'pengawasan_penggunaan' => [
        'model'         => 'App\\Models\\PmPengawasanPenggunaan',
        'perm'          => 'pemeliharaan_pengawasan',
        'modul'         => 'Pemeliharaan & Pengawasan',
        'judul'         => 'Pengawasan Penggunaan Aset',
        'maker_checker' => false,
        'fields'        => [
            'nama_aset' => [
                'label' => 'Nama Aset',
                'type'  => 'text',
                'list'  => true,
                'req'   => false,
            ],
            'tanggal' => [
                'label'   => 'Tanggal',
                'type'    => 'date',
                'list'    => true,
                'fmt'     => 'date',
                'req'     => true,
                'default' => 'today',
            ],
            'pengguna' => [
                'label' => 'Unit / Pengguna',
                'type'  => 'text',
                'list'  => true,
                'req'   => false,
            ],
            'uraian_penggunaan' => [
                'label' => 'Uraian Penggunaan',
                'type'  => 'textarea',
                'list'  => true,
                'req'   => false,
            ],
            'kesesuaian' => [
                'label' => 'Kesesuaian Penggunaan',
                'type'  => 'select',
                'list'  => true,
                'fmt'   => 'badge',
                'req'   => false,
                'opts'  => ['Sesuai', 'Tidak Sesuai', 'Perlu Evaluasi'],
            ],
            'catatan' => [
                'label' => 'Catatan',
                'type'  => 'textarea',
                'list'  => false,
                'req'   => false,
            ],
            'petugas' => [
                'label' => 'Petugas Pengawas',
                'type'  => 'text',
                'list'  => true,
                'req'   => false,
            ],
            'dokumen' => [
                'label' => 'Dokumen / Foto',
                'type'  => 'file',
                'list'  => false,
                'req'   => false,
            ],
        ],
    ],
    'tindak_lanjut_perbaikan' => [
        'model'         => 'App\\Models\\PmTindakLanjutPerbaikan',
        'perm'          => 'pemeliharaan_pengawasan',
        'modul'         => 'Pemeliharaan & Pengawasan',
        'judul'         => 'Tindak Lanjut Perbaikan',
        'maker_checker' => false,
        'fields'        => [
            'no_tindak_lanjut' => [
                'label' => 'No. TL',
                'type'  => 'text',
                'list'  => true,
                'req'   => false,
            ],
            'nama_aset' => [
                'label' => 'Nama Aset',
                'type'  => 'text',
                'list'  => true,
                'req'   => false,
            ],
            'sumber' => [
                'label' => 'Sumber Laporan',
                'type'  => 'select',
                'list'  => true,
                'fmt'   => 'badge',
                'req'   => false,
                'opts'  => ['Tiket', 'Inspeksi Mandiri', 'Pengawasan', 'Lainnya'],
            ],
            'uraian_kerusakan' => [
                'label' => 'Uraian Kerusakan',
                'type'  => 'textarea',
                'list'  => true,
                'req'   => false,
            ],
            'tanggal_laporan' => [
                'label'   => 'Tgl Dilaporkan',
                'type'    => 'date',
                'list'    => true,
                'fmt'     => 'date',
                'req'     => false,
                'default' => 'today',
            ],
            'tanggal_perbaikan' => [
                'label' => 'Tgl Perbaikan',
                'type'  => 'date',
                'list'  => true,
                'fmt'   => 'date',
                'req'   => false,
            ],
            'teknisi' => [
                'label' => 'Teknisi / Pelaksana',
                'type'  => 'text',
                'list'  => true,
                'req'   => false,
            ],
            'hasil_perbaikan' => [
                'label' => 'Hasil Perbaikan',
                'type'  => 'textarea',
                'list'  => false,
                'req'   => false,
            ],
            'status' => [
                'label' => 'Status',
                'type'  => 'select',
                'list'  => true,
                'fmt'   => 'badge',
                'req'   => false,
                'opts'  => ['Dilaporkan', 'Dalam Proses', 'Selesai', 'Ditangguhkan'],
            ],
            'dokumen' => [
                'label' => 'Dokumen / BAST',
                'type'  => 'file',
                'list'  => false,
                'req'   => false,
            ],
        ],
    ],
];
