<?php

// Konfigurasi mesin CRUD generik -- diekstrak 1:1 dari dictionary RES
// di portum.py (versi Python) supaya label, tipe field, opsi select,
// dan field mana yang wajib tetap identik dengan aplikasi lama.
// Dipakai oleh App\Http\Controllers\ModuleController.

return [
    'kendaraan' => [
        'model' => 'App\\Models\\UmKendaraan',
        'perm' => 'umum_rt',
        'modul' => 'Umum & Rumah Tangga',
        'judul' => 'Kendaraan & Driver',
        'maker_checker' => false,
        'fields' => [
            'no_polisi' => [
                'label' => 'No. Polisi',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'jenis' => [
                'label' => 'Jenis',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'merk' => [
                'label' => 'Merk',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'tahun' => [
                'label' => 'Tahun',
                'type' => 'text',
                'list' => false,
                'req' => false,
            ],
            'peruntukan' => [
                'label' => 'Peruntukan',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'driver' => [
                'label' => 'Driver',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Aktif', 'Servis', 'Nonaktif'],
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
        ],
    ],
    'biaya_harian' => [
        'model' => 'App\\Models\\UmBiayaHarian',
        'perm' => 'umum_rt',
        'modul' => 'Umum & Rumah Tangga',
        'judul' => 'Biaya BBM / Perawatan / Rumah Tangga',
        'maker_checker' => true,
        'fields' => [
            'tanggal' => [
                'label' => 'Tanggal',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => true,
            ],
            'kategori' => [
                'label' => 'Kategori',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => true,
                'opts' => ['BBM', 'Perawatan', 'Rumah Tangga'],
            ],
            'kendaraan' => [
                'label' => 'Kendaraan',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'nama_beban' => [
                'label' => 'Nama Beban (Akun)',
                'type' => 'select',
                'list' => false,
                'req' => false,
                'opts_sql' => 'SELECT nama_beban AS v, nama_beban || " — " || rekening_debet AS t FROM ref_akun ORDER BY nama_beban',
            ],
            'rekening_debet' => [
                'label' => 'Rekening Debet',
                'type' => 'text',
                'list' => false,
                'req' => false,
            ],
            'rekening_kredit' => [
                'label' => 'Rekening Kredit',
                'type' => 'text',
                'list' => false,
                'req' => false,
            ],
            'uraian' => [
                'label' => 'Uraian',
                'type' => 'textarea',
                'list' => true,
                'req' => false,
            ],
            'jumlah' => [
                'label' => 'Jumlah',
                'type' => 'money',
                'list' => true,
                'fmt' => 'money',
                'req' => false,
            ],
            'no_nota' => [
                'label' => 'No. Nota',
                'type' => 'text',
                'list' => false,
                'req' => false,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Draft', 'Diajukan', 'Dibukukan'],
            ],
            'dibuat_oleh' => [
                'label' => 'Dibuat Oleh',
                'type' => 'auto_user',
                'list' => false,
                'req' => false,
            ],
            'dokumen' => [
                'label' => 'Dokumen (Lampiran)',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    'permintaan_cabang' => [
        'model' => 'App\\Models\\UmPermintaanCabang',
        'perm' => 'umum_rt',
        'modul' => 'Umum & Rumah Tangga',
        'judul' => 'Permintaan Cabang (ATK/Inventaris)',
        'maker_checker' => true,
        'fields' => [
            'no_permintaan' => [
                'label' => 'No. Permintaan',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'tanggal' => [
                'label' => 'Tanggal',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => true,
            ],
            'unit_kerja' => [
                'label' => 'Unit Kerja / Cabang',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'jenis' => [
                'label' => 'Jenis',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['ATK', 'Inventaris', 'Perbaikan', 'Lainnya'],
            ],
            'uraian' => [
                'label' => 'Uraian',
                'type' => 'textarea',
                'list' => true,
                'req' => false,
            ],
            'jumlah' => [
                'label' => 'Jumlah',
                'type' => 'text',
                'list' => false,
                'req' => false,
            ],
            'satuan' => [
                'label' => 'Satuan',
                'type' => 'text',
                'list' => false,
                'req' => false,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Diajukan', 'Disetujui', 'Diproses', 'Selesai', 'Ditolak'],
            ],
            'petugas' => [
                'label' => 'Petugas',
                'type' => 'text',
                'list' => false,
                'req' => false,
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
            'dokumen' => [
                'label' => 'Dokumen (Lampiran)',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    'invoice_sewa' => [
        'model' => 'App\\Models\\AsInvoiceSewa',
        'perm' => 'aset_logistik',
        'modul' => 'Aset & Logistik',
        'judul' => 'Tagihan / Invoice Sewa',
        'maker_checker' => false,
        'fields' => [
            'no_invoice' => [
                'label' => 'No. Invoice',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'vendor' => [
                'label' => 'Vendor',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'jenis_sewa' => [
                'label' => 'Jenis Sewa',
                'type' => 'select',
                'list' => true,
                'req' => false,
                'opts' => ['Aplikasi', 'Mesin ATM', 'Brankas', 'Perangkat IT', 'Software', 'Hardware'],
            ],
            'periode_mulai' => [
                'label' => 'Periode Mulai',
                'type' => 'date',
                'list' => false,
                'req' => false,
            ],
            'periode_selesai' => [
                'label' => 'Periode Selesai',
                'type' => 'date',
                'list' => false,
                'req' => false,
            ],
            'nilai' => [
                'label' => 'Nilai',
                'type' => 'money',
                'list' => true,
                'fmt' => 'money',
                'req' => false,
            ],
            'jatuh_tempo' => [
                'label' => 'Jatuh Tempo',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => false,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Belum Bayar', 'Proses', 'Lunas'],
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
            'dokumen' => [
                'label' => 'Dokumen (Lampiran)',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    'aset' => [
        'model' => 'App\\Models\\AsAset',
        'perm' => 'aset_logistik',
        'modul' => 'Aset & Logistik',
        'judul' => 'Inventarisasi Aset',
        'maker_checker' => false,
        'fields' => [
            'kode_aset' => [
                'label' => 'Kode Aset',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'nama_aset' => [
                'label' => 'Nama Aset',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'kategori' => [
                'label' => 'Kategori',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'lokasi' => [
                'label' => 'Lokasi',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'tanggal_perolehan' => [
                'label' => 'Tgl Perolehan',
                'type' => 'date',
                'list' => false,
                'fmt' => 'date',
                'req' => false,
            ],
            'nilai_perolehan' => [
                'label' => 'Nilai Perolehan',
                'type' => 'money',
                'list' => true,
                'fmt' => 'money',
                'req' => false,
            ],
            'umur_ekonomis' => [
                'label' => 'Umur Ekonomis (bln)',
                'type' => 'number',
                'list' => false,
                'req' => false,
            ],
            'kondisi' => [
                'label' => 'Kondisi',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Baik', 'Rusak Ringan', 'Rusak Berat'],
            ],
            'penanggung_jawab' => [
                'label' => 'Penanggung Jawab',
                'type' => 'text',
                'list' => false,
                'req' => false,
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
        ],
    ],
    'amortisasi' => [
        'model' => 'App\\Models\\AsAmortisasi',
        'perm' => 'aset_logistik',
        'modul' => 'Aset & Logistik',
        'judul' => 'Amortisasi Biaya',
        'maker_checker' => false,
        'fields' => [
            'nama_biaya' => [
                'label' => 'Nama Biaya',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'nilai_perolehan' => [
                'label' => 'Nilai Perolehan',
                'type' => 'money',
                'list' => true,
                'fmt' => 'money',
                'req' => false,
            ],
            'tanggal_mulai' => [
                'label' => 'Tgl Mulai',
                'type' => 'date',
                'list' => false,
                'fmt' => 'date',
                'req' => false,
            ],
            'umur_bulan' => [
                'label' => 'Umur (bulan)',
                'type' => 'number',
                'list' => true,
                'req' => false,
            ],
            'nilai_per_bulan' => [
                'label' => 'Nilai / Bulan',
                'type' => 'money',
                'list' => true,
                'fmt' => 'money',
                'req' => false,
                'help' => 'Dihitung otomatis bila dikosongkan (nilai ÷ umur)',
            ],
            'akumulasi' => [
                'label' => 'Akumulasi',
                'type' => 'money',
                'list' => false,
                'fmt' => 'money',
                'req' => false,
            ],
            'nilai_buku' => [
                'label' => 'Nilai Buku',
                'type' => 'money',
                'list' => true,
                'fmt' => 'money',
                'req' => false,
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
        ],
    ],
    'pks' => [
        'model' => 'App\\Models\\AsPks',
        'perm' => 'aset_logistik',
        'modul' => 'Aset & Logistik',
        'judul' => 'PKS & Jatuh Tempo',
        'maker_checker' => true,
        'fields' => [
            'no_pks' => [
                'label' => 'No. PKS',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'judul' => [
                'label' => 'Judul PKS',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'vendor' => [
                'label' => 'Vendor / Pihak',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'div_owner' => [
                'label' => 'Divisi Owner',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'tanggal_mulai' => [
                'label' => 'Tgl Mulai',
                'type' => 'date',
                'list' => false,
                'fmt' => 'date',
                'req' => false,
            ],
            'jatuh_tempo' => [
                'label' => 'Jatuh Tempo',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => false,
            ],
            'nilai' => [
                'label' => 'Nilai',
                'type' => 'money',
                'list' => false,
                'fmt' => 'money',
                'req' => false,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Aktif', 'Akan Jatuh Tempo', 'Berakhir', 'Diperpanjang'],
            ],
            'memo_dibuat' => [
                'label' => 'Memo ke Div Owner Dibuat',
                'type' => 'checkbox',
                'list' => true,
                'req' => false,
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
            'dokumen' => [
                'label' => 'Dokumen (Lampiran)',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    'memo_sewa_cabang' => [
        'model' => 'App\\Models\\AsMemoSewaCabang',
        'perm' => 'aset_logistik',
        'modul' => 'Aset & Logistik',
        'judul' => 'Memo Sewa Cabang',
        'maker_checker' => true,
        'fields' => [
            'no_memo' => [
                'label' => 'No. Memo',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'cabang' => [
                'label' => 'Cabang',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'jenis' => [
                'label' => 'Jenis Sewa',
                'type' => 'select',
                'list' => true,
                'req' => false,
                'opts' => ['Galeri ATM', 'Gedung Kantor', 'Gudang', 'Rumah Dinas'],
            ],
            'tanggal' => [
                'label' => 'Tanggal',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => false,
            ],
            'nilai' => [
                'label' => 'Nilai',
                'type' => 'money',
                'list' => true,
                'fmt' => 'money',
                'req' => false,
            ],
            'status_persetujuan' => [
                'label' => 'Status Persetujuan',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Diajukan', 'Persetujuan Prinsip', 'Disetujui', 'Ditolak'],
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
            'dokumen' => [
                'label' => 'Dokumen (Lampiran)',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    'temuan' => [
        'model' => 'App\\Models\\AsTemuan',
        'perm' => 'aset_logistik',
        'modul' => 'Aset & Logistik',
        'judul' => 'Tindak Lanjut Temuan',
        'maker_checker' => false,
        'fields' => [
            'no_temuan' => [
                'label' => 'No. Temuan',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'sumber' => [
                'label' => 'Sumber',
                'type' => 'select',
                'list' => true,
                'req' => false,
                'opts' => ['Audit Internal', 'OJK', 'KAP', 'Lainnya'],
            ],
            'uraian' => [
                'label' => 'Uraian Temuan',
                'type' => 'textarea',
                'list' => true,
                'req' => true,
            ],
            'tanggal_temuan' => [
                'label' => 'Tgl Temuan',
                'type' => 'date',
                'list' => false,
                'fmt' => 'date',
                'req' => false,
            ],
            'batas_tindak_lanjut' => [
                'label' => 'Batas Tindak Lanjut',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => false,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Open', 'Proses', 'Selesai'],
            ],
            'penanggung_jawab' => [
                'label' => 'Penanggung Jawab',
                'type' => 'text',
                'list' => false,
                'req' => false,
            ],
            'tindak_lanjut' => [
                'label' => 'Tindak Lanjut',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
            'dokumen' => [
                'label' => 'Dokumen (Lampiran)',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    'memo_internal' => [
        'model' => 'App\\Models\\PgMemoInternal',
        'perm' => 'pengadaan',
        'modul' => 'Pengadaan & Pemeliharaan',
        'judul' => 'Memo Internal',
        'maker_checker' => false,
        'fields' => [
            'no_memo' => [
                'label' => 'No. Memo',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'dari_unit' => [
                'label' => 'Dari Unit',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'ke_unit' => [
                'label' => 'Ke Unit',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'perihal' => [
                'label' => 'Perihal',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'tanggal' => [
                'label' => 'Tanggal',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => false,
            ],
            'jenis' => [
                'label' => 'Jenis',
                'type' => 'select',
                'list' => false,
                'req' => false,
                'opts' => ['Divisi', 'Cabang', 'Cabang Pembantu', 'Kantor Kas'],
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Masuk', 'Diproses', 'Selesai'],
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
            'dokumen' => [
                'label' => 'Dokumen (Lampiran)',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    'penawaran' => [
        'model' => 'App\\Models\\PgPenawaran',
        'perm' => 'pengadaan',
        'modul' => 'Pengadaan & Pemeliharaan',
        'judul' => 'Penawaran Vendor',
        'maker_checker' => false,
        'fields' => [
            'no_penawaran' => [
                'label' => 'No. Penawaran',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'vendor' => [
                'label' => 'Vendor',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'barang_jasa' => [
                'label' => 'Barang / Jasa',
                'type' => 'textarea',
                'list' => true,
                'req' => false,
            ],
            'nilai' => [
                'label' => 'Nilai Penawaran',
                'type' => 'money',
                'list' => true,
                'fmt' => 'money',
                'req' => false,
            ],
            'tanggal' => [
                'label' => 'Tanggal',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => false,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Diterima', 'Evaluasi', 'Negosiasi', 'Ditolak'],
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
            'dokumen' => [
                'label' => 'Dokumen (Lampiran)',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    'negosiasi' => [
        'model' => 'App\\Models\\PgNegosiasi',
        'perm' => 'pengadaan',
        'modul' => 'Pengadaan & Pemeliharaan',
        'judul' => 'Negosiasi (Berita Acara)',
        'maker_checker' => false,
        'fields' => [
            'no_berita_acara' => [
                'label' => 'No. Berita Acara',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'vendor' => [
                'label' => 'Vendor',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'barang_jasa' => [
                'label' => 'Barang / Jasa',
                'type' => 'textarea',
                'list' => true,
                'req' => false,
            ],
            'nilai_awal' => [
                'label' => 'Nilai Awal',
                'type' => 'money',
                'list' => true,
                'fmt' => 'money',
                'req' => false,
            ],
            'nilai_nego' => [
                'label' => 'Nilai Nego',
                'type' => 'money',
                'list' => true,
                'fmt' => 'money',
                'req' => false,
            ],
            'tanggal' => [
                'label' => 'Tanggal',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => false,
            ],
            'hasil' => [
                'label' => 'Hasil',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
            'dokumen' => [
                'label' => 'Dokumen (Lampiran)',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    'draft_dokumen' => [
        'model' => 'App\\Models\\PgDraftDokumen',
        'perm' => 'pengadaan',
        'modul' => 'Pengadaan & Pemeliharaan',
        'judul' => 'Draft Dokumen (PKS/NDA/SPK)',
        'maker_checker' => false,
        'fields' => [
            'jenis' => [
                'label' => 'Jenis',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['PKS', 'NDA', 'SPK', 'Lainnya'],
            ],
            'no_dokumen' => [
                'label' => 'No. Dokumen',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'judul' => [
                'label' => 'Judul',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'vendor' => [
                'label' => 'Vendor',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'tanggal' => [
                'label' => 'Tanggal',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => false,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Draft', 'Review', 'Final'],
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
            'file' => [
                'label' => 'Dokumen (Lampiran)',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    'spk' => [
        'model' => 'App\\Models\\PgSpk',
        'perm' => 'pengadaan',
        'modul' => 'Pengadaan & Pemeliharaan',
        'judul' => 'SPK (Surat Perintah Kerja)',
        'maker_checker' => true,
        'fields' => [
            'no_spk' => [
                'label' => 'No. SPK',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'vendor' => [
                'label' => 'Vendor',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'pekerjaan' => [
                'label' => 'Pekerjaan',
                'type' => 'textarea',
                'list' => true,
                'req' => false,
            ],
            'nilai' => [
                'label' => 'Nilai',
                'type' => 'money',
                'list' => true,
                'fmt' => 'money',
                'req' => false,
            ],
            'tanggal_terbit' => [
                'label' => 'Tgl Terbit',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => false,
            ],
            'tanggal_selesai' => [
                'label' => 'Tgl Selesai',
                'type' => 'date',
                'list' => false,
                'fmt' => 'date',
                'req' => false,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Berjalan', 'Selesai', 'Batal'],
            ],
            'keterangan' => [
                'label' => 'Keterangan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
            'dokumen' => [
                'label' => 'Dokumen (Lampiran)',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    'reminder' => [
        'model' => 'App\\Models\\PgReminder',
        'perm' => 'pengadaan',
        'modul' => 'Pengadaan & Pemeliharaan',
        'judul' => 'Reminder Schedule',
        'maker_checker' => false,
        'fields' => [
            'judul' => [
                'label' => 'Judul',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'kategori' => [
                'label' => 'Kategori',
                'type' => 'select',
                'list' => true,
                'req' => true,
                'opts' => ['PKS', 'Sewa', 'SPK', 'Pemeliharaan', 'Lainnya'],
            ],
            'tanggal_jatuh_tempo' => [
                'label' => 'Tgl Jatuh Tempo',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => true,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'list' => true,
                'fmt' => 'badge',
                'req' => false,
                'opts' => ['Aktif', 'Selesai'],
            ],
            'catatan' => [
                'label' => 'Catatan',
                'type' => 'textarea',
                'list' => false,
                'req' => false,
            ],
        ],
    ],
    'ref_akun' => [
        'model' => 'App\\Models\\RefAkun',
        'perm' => 'ref_akun',
        'modul' => 'Pengaturan',
        'judul' => 'Referensi Akun Biaya',
        'maker_checker' => false,
        'fields' => [
            'nama_beban' => [
                'label' => 'Nama Beban',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'rekening_debet' => [
                'label' => 'Rekening Debet',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'contoh_keterangan' => [
                'label' => 'Contoh Keterangan',
                'type' => 'textarea',
                'list' => true,
                'req' => false,
            ],
        ],
    ],
    'surat_masuk' => [
        'model' => 'App\\Models\\SrSuratMasuk',
        'perm' => 'risalah',
        'modul' => 'Arsip Surat & Memo',
        'judul' => 'Surat Masuk',
        'maker_checker' => false,
        'fields' => [
            'nomor_agenda' => [
                'label' => 'Nomor Agenda',
                'type' => 'number',
                'list' => true,
                'req' => true,
                'help' => 'Rekomendasi otomatis (+10 setiap hari baru, +1 di hari yang sama) — boleh diubah / disisip nomor untuk tanggal sebelumnya.',
            ],
            'no_surat' => [
                'label' => 'No. Surat',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'pengirim' => [
                'label' => 'Pengirim',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'perihal' => [
                'label' => 'Perihal',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'tanggal' => [
                'label' => 'Tanggal',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => true,
                'default' => 'today',
            ],
            'penerima' => [
                'label' => 'Penerima',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'lokasi_arsip' => [
                'label' => 'Lokasi Arsip',
                'type' => 'text',
                'list' => true,
                'req' => false,
                'help' => 'cth: Lemari A / Ordner 3 / Map Merah',
            ],
            'lampiran' => [
                'label' => 'Lampiran',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
            'dibuat_oleh' => [
                'label' => 'Dibuat Oleh',
                'type' => 'auto_user',
                'list' => false,
                'req' => false,
            ],
        ],
    ],
    'surat_keluar' => [
        'model' => 'App\\Models\\SrSuratKeluar',
        'perm' => 'risalah',
        'modul' => 'Arsip Surat & Memo',
        'judul' => 'Surat Keluar',
        'maker_checker' => false,
        'fields' => [
            'nomor_agenda' => [
                'label' => 'Nomor Agenda',
                'type' => 'number',
                'list' => true,
                'req' => true,
                'help' => 'Rekomendasi otomatis (+10 setiap hari baru, +1 di hari yang sama) — boleh diubah / disisip nomor untuk tanggal sebelumnya.',
            ],
            'no_surat' => [
                'label' => 'No. Surat',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'pengirim' => [
                'label' => 'Pengirim (Unit)',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'perihal' => [
                'label' => 'Perihal',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'tanggal' => [
                'label' => 'Tanggal',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => true,
                'default' => 'today',
            ],
            'penerima' => [
                'label' => 'Penerima / Tujuan',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'lokasi_arsip' => [
                'label' => 'Lokasi Arsip',
                'type' => 'text',
                'list' => true,
                'req' => false,
                'help' => 'cth: Lemari A / Ordner 3 / Map Merah',
            ],
            'lampiran' => [
                'label' => 'Lampiran',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
            'dibuat_oleh' => [
                'label' => 'Dibuat Oleh',
                'type' => 'auto_user',
                'list' => false,
                'req' => false,
            ],
        ],
    ],
    'memo_masuk' => [
        'model' => 'App\\Models\\SrMemoMasuk',
        'perm' => 'risalah',
        'modul' => 'Arsip Surat & Memo',
        'judul' => 'Memo Masuk',
        'maker_checker' => false,
        'fields' => [
            'nomor_agenda' => [
                'label' => 'Nomor Agenda',
                'type' => 'number',
                'list' => true,
                'req' => true,
                'help' => 'Rekomendasi otomatis (+10 setiap hari baru, +1 di hari yang sama) — boleh diubah / disisip nomor untuk tanggal sebelumnya.',
            ],
            'no_surat' => [
                'label' => 'No. Surat',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'pengirim' => [
                'label' => 'Pengirim',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'perihal' => [
                'label' => 'Perihal',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'tanggal' => [
                'label' => 'Tanggal',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => true,
                'default' => 'today',
            ],
            'penerima' => [
                'label' => 'Penerima',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'lokasi_arsip' => [
                'label' => 'Lokasi Arsip',
                'type' => 'text',
                'list' => true,
                'req' => false,
                'help' => 'cth: Lemari A / Ordner 3 / Map Merah',
            ],
            'lampiran' => [
                'label' => 'Lampiran',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
            'dibuat_oleh' => [
                'label' => 'Dibuat Oleh',
                'type' => 'auto_user',
                'list' => false,
                'req' => false,
            ],
        ],
    ],
    'memo_keluar' => [
        'model' => 'App\\Models\\SrMemoKeluar',
        'perm' => 'risalah',
        'modul' => 'Arsip Surat & Memo',
        'judul' => 'Memo Keluar',
        'maker_checker' => false,
        'fields' => [
            'nomor_agenda' => [
                'label' => 'Nomor Agenda',
                'type' => 'number',
                'list' => true,
                'req' => true,
                'help' => 'Rekomendasi otomatis (+10 setiap hari baru, +1 di hari yang sama) — boleh diubah / disisip nomor untuk tanggal sebelumnya.',
            ],
            'no_surat' => [
                'label' => 'No. Surat',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'pengirim' => [
                'label' => 'Pengirim (Unit)',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'perihal' => [
                'label' => 'Perihal',
                'type' => 'text',
                'list' => true,
                'req' => true,
            ],
            'tanggal' => [
                'label' => 'Tanggal',
                'type' => 'date',
                'list' => true,
                'fmt' => 'date',
                'req' => true,
                'default' => 'today',
            ],
            'penerima' => [
                'label' => 'Penerima / Tujuan',
                'type' => 'text',
                'list' => true,
                'req' => false,
            ],
            'lokasi_arsip' => [
                'label' => 'Lokasi Arsip',
                'type' => 'text',
                'list' => true,
                'req' => false,
                'help' => 'cth: Lemari A / Ordner 3 / Map Merah',
            ],
            'lampiran' => [
                'label' => 'Lampiran',
                'type' => 'file',
                'list' => true,
                'req' => false,
            ],
            'dibuat_oleh' => [
                'label' => 'Dibuat Oleh',
                'type' => 'auto_user',
                'list' => false,
                'req' => false,
            ],
        ],
    ],
];
